---
configure_sudoers: yes
configure_terminal: no
configure_osx: yes
configure_dock: yes

dotfiles_repo: https://github.com/oxyc/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
dotfiles_files:
  - .ignore
  - .bash_profile
  - .bashrc
  - .chunkwmrc
  - .dircolors
  - .gitconfig
  - .gitignore
  - .inputrc
  - .khdrc
  - .lftprc
  - .bash_sessions_disable
  - .bash/aliases.sh
  - .bash/colors.sh
  - .bash/completions.sh
  - .bash/exports.sh
  - .bash/functions.sh
  - .bash/prompt.sh
  - .bash/shell.sh
  - .bash/ssh-agent.sh
  - .osx/osx.sh
  - .weechat/irc.conf
  - .weechat/lua/autoload/matrix.lua
  - .weechat/perl/autoload/buffers.pl
  - .weechat/plugins.conf
  - .weechat/plugins/scripts/perl/buffers.pl
  - .weechat/plugins/weechat-matrix-protocol-script/matrix.lua
  - .weechat/plugins/weechat-notification-center/notification_center.py
  - .weechat/python/autoload/notification_center.py
  - .weechat/python/autoload/wee_slack.py
  - .weechat/script.conf
  - .weechat/weechat.conf
  - .weechat/weechat.png
  - .weechat/xfer.conf

homebrew_installed_packages:
  # Install GNU packages.
  # https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
  - coreutils
  - binutils
  - diffutils
  - { name: ed, install_options: "default-names" }
  - { name: findutils, install_options: "with-default-names" }
  - gawk
  - { name: gnu-indent, install_options: "with-default-names" }
  - { name: gnu-sed, install_options: "with-default-names" }
  - { name: gnu-tar, install_options: "with-default-names" }
  - { name: gnu-which, install_options: "with-default-names" }
  - gnutls
  - { name: grep, install_options: "with-default-names" }
  - gzip
  - screen
  - watch
  - { name: wdiff, install_options: "with-gettext" }
  - wget
  # Update GNU pre-installed packages.
  - bash
  - emacs
  - gdb
  - gpatch
  - less
  - m4
  - make
  - nano
  # Update non-GNU pre-installed packages.
  - file-formula
  - git
  - openssh
  - perl
  - python
  - rsync
  - svn
  - unzip

  # Some other GNU tools.
  - autoconf                  # build tool
  - gettext                   # gnu translation tool
  - gpg                       # gnu privacy guard
  - readline                  # gnu readline

  # More terminal tools.
  - git-standup               # recall what you did on the last working day
  - httpie                    # cli http client
  - iperf                     # bandwidth benchmarking
  - lynx                      # browser
  - nmap                      # network mapper
  - openssl                   # ssl/tls toolkit
  - p7zip                     # 7 zip
  - pigz                      # parallel gzip
  - pv                        # pipe viewer
  - { name: weechat, install_options: "with-perl,with-python,with-lua" }
  - wrk                       # http benchmarking
  - zopfli                    # zopfli compression

  # Programming languages
  - lua
  - node
  - go
  - { name: php71, install_options: "with-pear,without-fpm" }
  - python3
  - ruby

  # Libraries
  - luajit                    # required by vim
  - duti                      # required by tasks/default-applications.yml

  # Essential development tools/libraries.
  - { name: base16-shell, install_options: "HEAD" } # base16 colors in shell
  - { name: chunkwm, install_options: "without-border" } # tiling window manager
  - exa                       # ls replacement
  - fasd                      # autojump
  - fzf                       # fuzzy finder
  - khd                       # hotkey daemon
  - massren                   # mass renaming in vim
  - mosh                      # mobile shell
  - rename                    # regex rename
  - ssh-copy-id               # send public key to remote
  - the_silver_searcher       # ag, faster than ack
  - tree                      # recursive directory listing
  - { name: vim, install_options: "with-luajit,without-ruby,with-override-system-vi" }
  - neovim                    # the new vim

  # Package managers
  - composer

  # Shell completions
  - bash-completion2         # bash 4
  - cap-completion           # capistrano
  - open-completion          # open
  - vagrant-completion       # vagrant
  - wpcli-completion         # wp-cli

  # Image/Video tools
  - exiv2
  - name: ffmpeg
    install_options: "with-fdk-aac,with-ffplay,with-freetype,with-libass,with-libquvi,with-libvorbis,with-libvpx,with-opus,with-x265"
  - gifsicle
  - { name: imagemagick, install_options: "with-webp" }
  - mozjpeg
  - optipng
  - pngcheck
  - webp

  # Install font tools.
  - sfnt2woff
  - sfnt2woff-zopfli
  - woff2

homebrew_taps:
  - bramstein/webfonttools # font tools
  - caskroom/cask          # casks
  - caskroom/fonts         # inconsolata font
  - caskroom/versions      # iterm2-beta
  - crisidev/homebrew-chunkwm # chunkwm
  - homebrew/core          #
  - homebrew/php           #
  - koekeishiya/formulae   # chunkwm, khd
  - laurent22/massren      # massren
  - oxyc/custom            # base16-shell, kitty
  - neovim/neovim          # neovim

homebrew_cask_apps:
  - alfred                 # launcher
  - adobe-dng-converter    # arw -> dng
  - clipy                  # clipboard manager
  - docker                 # work
  - filezilla              # ftp gui
  - firefox                # crossbrowser testing
  - font-inconsolata-dz-for-powerline # dev font
  - google-chrome          # primary browser
  - iina                   # movie player
  - iterm2-beta            # beta for no-window-bar
  - lastpass               # browser plugins
  - macdown                # markdown editor
  - macvim                 # text editor
  - playmemories-home      # sony camera
  - skype                  # work
  - slack                  # work
  - sublime-text           # work
  - transmission           # torrents
  - vagrant                # work
  - virtualbox             # work
  # Quick Look plugins
  - qlcolorcode            # syntax highlighting
  - qlstephen              # files without file extensions
  - qlmarkdown             # markdown
  - quicklook-json         # json
  - quicklook-csv          # csv
  - qlimagesize            # display image size and resolution
  - webpquicklook          # webp

homebrew_services:
  - khd                    # hotkey daemon

osx_script: ~/.osx/osx.sh

composer_packages:
  - name: hirak/prestissimo    # parallel composer downloads
  - name: wp-cli/wp-cli        # wp cli tool
  - { name: drush/drush, version: '^8.1' } # drupal cli tool
  - name: asm89/twig-lint      # vim linter for twig

npm_packages:
  - name: yarn                 # package manager
  - name: webpack              # build tool
  - name: bower                # package manager
  - name: gulp                 # build tool
  - name: svgo                 # svg minifier
  - name: jsonlint             # vim linter for json
  - name: markdownlint-cli     # vim linter for markdown
  - name: eslint               # vim linter for javascript
  - name: eslint-plugin-import # dependency of global eslint

gem_packages:
  - name: bundler              # package manager
  - name: capistrano           # deploy tool
  - name: jekyll               # github pages
  - name: jekyll-feed          # github pages
  - name: rubocop              # drupal vm lint
  - name: neovim               # ruby provider for neovim
  - name: sass                 # vim linter for sass

pip_packages:
  - name: mkdocs                       # drupal vm docs
  - { name: neovim, executable: pip2 } # python2 provider for neovim
  - { name: neovim, executable: pip3 } # python3 provider for neovim
  - name: ansible-lint                 # vim linter for ansible
  - name: yamllint                     # vim linter for bash
  - name: proselint                    # vim linter for text
  - name: pync                         # weechat notification_center plugin
  - name: websocket-client             # weechat wee_slack plugin

luarocks_packages:
  - name: lua-cjson                    # weechat matrix plugin

post_provision_tasks: "{{ playbook_dir }}/../tasks/*.yml"

# fubarhouse.macdock settings.
dockitems_disabled:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 2
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 3
  - name: Activity Monitor
    path: "/Applications/Utilities/Activity Monitor.app"
    pos: 4

# Variables used across tasks/*.yml
local_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

# tasks/vagrant.yml settings.
vagrant_plugins_force_install: false
vagrant_plugins:
  - vagrant-hostsupdater
  - vagrant-vbguest

# tasks/vim.yml settings.
vimrc_repo: https://github.com/oxyc/vimrc.git
vimrc_repo_local_destination: ~/Projects/Personal/vimrc

# tasks/iterm2.yml settings.
iterm2_enable_automatic_updates: true
iterm2_preference_folder: "{{ playbook_dir }}/../files"

# tasks/default-applications.yml
default_applications:
  # Iina
  - { extension: avi, handler: com.colliderli.iina }
  - { extension: flv, handler: com.colliderli.iina }
  - { extension: mkv, handler: com.colliderli.iina }
  - { extension: mov, handler: com.colliderli.iina }
  - { extension: mp4, handler: com.colliderli.iina }
  - { extension: mpg, handler: com.colliderli.iina }
  # MacDown
  - { extension: md, handler: com.uranusjr.macdown }
  # Chrome
  - { extension: html, handler: com.google.Chrome, roles: '' }
  - { extension: xml, handler: com.google.Chrome }
  # MacVim
  - { extension: cfg, handler: org.vim.MacVim }
  - { extension: css, handler: org.vim.MacVim }
  - { extension: inc, handler: org.vim.MacVim }
  - { extension: js, handler: org.vim.MacVim }
  - { extension: json, handler: org.vim.MacVim }
  - { extension: php, handler: org.vim.MacVim }
  - { extension: scss, handler: org.vim.MacVim }
  - { extension: txt, handler: org.vim.MacVim }
  - { extension: yml, handler: org.vim.MacVim }

# tasks/iina.yml settings.
iina_keybinding_file: "{{ playbook_dir }}/../files/Iina.keybindings.conf"

# tasks/git.yml settings.
git_user_name: "Oskar Schöldström"
git_user_email: m@oxy.fi
git_signingkey: B1E80EF9EBBB2973
git_github_user: oxyc
